### ISSUE TITLE
Can you please update minimum version as 14

### ISSUE THREAD

**Issue by darish** [allan1st/JellyRefreshLayout#1]

**Comment by imallan** [comment]
@darish I would love to. 
Currently the first release set the minSDKVersion to 19 since I've used an API call only available on 19+.  (ViewPropertyAnimator::setUpdateListener)
Older versions support will be available in next release. Sorry for that.
Feel free to fork the code. You can simply replace ViewPropertyAnimator with ValueAnimator which gives you compatibility back to API level 11.
